/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package hub.sam.tef.etsl.validation;

import hub.sam.tef.etsl.Rhs;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link hub.sam.tef.etsl.RhsSequence}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RhsSequenceValidator {
	boolean validate();

	boolean validateParts(EList<Rhs> value);
}
