/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package hub.sam.sdl.validation;


/**
 * A sample validator interface for {@link hub.sam.sdl.CoreAbstractionsMultiplicitiesMultiplicityElement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CoreAbstractionsMultiplicitiesMultiplicityElementValidator {
	boolean validate();

	boolean validateIsOrdered(boolean value);

	boolean validateIsUnique(boolean value);

	boolean validateLower(int value);

	boolean validateUpper(int value);

	boolean validateIsOrdered(String value);
	boolean validateIsUnique(String value);
	boolean validateLower(String value);
	boolean validateUpper(String value);
}
