/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package hub.sam.sdl.validation;

import hub.sam.sdl.CoreAbstractionsExpressionsValueSpecification;

/**
 * A sample validator interface for {@link hub.sam.sdl.CoreAbstractionsMultiplicityExpressionsMultiplicityElement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CoreAbstractionsMultiplicityExpressionsMultiplicityElementValidator {
	boolean validate();

	boolean validateLower(int value);

	boolean validateUpper(int value);

	boolean validateLower(String value);
	boolean validateUpper(String value);
	boolean validateUpperValue(CoreAbstractionsExpressionsValueSpecification value);
	boolean validateLowerValue(CoreAbstractionsExpressionsValueSpecification value);
}
