/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package hub.sam.sdl.validation;

import hub.sam.sdl.ConcreteSyntaxSdlIdentifier;
import hub.sam.sdl.CoreAbstractionsNamespacesNamespace;

/**
 * A sample validator interface for {@link hub.sam.sdl.CoreAbstractionsNamespacesNamedElement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CoreAbstractionsNamespacesNamedElementValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateQualifiedName(String value);
	boolean validateNamespace(CoreAbstractionsNamespacesNamespace value);
	boolean validateIdentifier(ConcreteSyntaxSdlIdentifier value);
}
