/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package hub.sam.sdl.validation;

import hub.sam.sdl.CoreAbstractionsConstraintsConstraint;
import hub.sam.sdl.CoreAbstractionsConstraintsNamedElement;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link hub.sam.sdl.CoreAbstractionsConstraintsNamespace}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CoreAbstractionsConstraintsNamespaceValidator {
	boolean validate();

	boolean validateOwnedRule(EList<CoreAbstractionsConstraintsConstraint> value);
	boolean validateOwnedMember(EList<CoreAbstractionsConstraintsNamedElement> value);
	boolean validateMember(EList<CoreAbstractionsConstraintsNamedElement> value);
}
