/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package hub.sam.sdl.validation;

import hub.sam.sdl.EvaluationEvaluation;
import hub.sam.sdl.InstanciationValue;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link hub.sam.sdl.EvaluationEvaluation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EvaluationEvaluationValidator {
	boolean validate();

	boolean validateSubEvaluation(EList<EvaluationEvaluation> value);
	boolean validateEvaluation_value(InstanciationValue value);
}
