/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package hub.sam.sdl.validation;

import hub.sam.sdl.CoreAbstractionsBehavioralFeaturesBehavioralFeature;
import hub.sam.sdl.EvaluationExpression;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link hub.sam.sdl.EvaluationBehavioralFeatureAccessExpression}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EvaluationBehavioralFeatureAccessExpressionValidator {
	boolean validate();

	boolean validateArgument(EList<EvaluationExpression> value);
	boolean validateBehavioralFeatureAccessExpression_feature(CoreAbstractionsBehavioralFeaturesBehavioralFeature value);
}
