/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package hub.sam.sdl.validation;

import hub.sam.sdl.SdlAgentInstance;
import hub.sam.sdl.SdlAgentInstanceSet;
import hub.sam.sdl.SdlCompositeStateInstance;

/**
 * A sample validator interface for {@link hub.sam.sdl.SdlAgentInstance}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SdlAgentInstanceValidator {
	boolean validate();

	boolean validateAgentInstanceSet(SdlAgentInstanceSet value);
	boolean validateBehavior(SdlCompositeStateInstance value);
	boolean validateOwningInstanceSet(SdlAgentInstanceSet value);
	boolean validateParent(SdlAgentInstance value);
	boolean validateOffspring(SdlAgentInstance value);
}
