/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package hub.sam.sdl.validation;

import hub.sam.sdl.SdlAgent;
import hub.sam.sdl.SdlAgentKind;
import hub.sam.sdl.SdlAgentType;
import hub.sam.sdl.SdlChannel;
import hub.sam.sdl.SdlCompositeState;
import hub.sam.sdl.SdlGate;
import hub.sam.sdl.SdlParameter;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link hub.sam.sdl.SdlAgentType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SdlAgentTypeValidator {
	boolean validate();

	boolean validateAgent(EList<SdlAgent> value);
	boolean validateKind(SdlAgentKind value);
	boolean validateOwnedAgentType(EList<SdlAgentType> value);
	boolean validateChannel(EList<SdlChannel> value);
	boolean validateBehavior(SdlCompositeState value);
	boolean validateParameter(EList<SdlParameter> value);
	boolean validateGate(EList<SdlGate> value);
}
