/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package hub.sam.sdl.validation;

import hub.sam.sdl.SdlAgent;
import hub.sam.sdl.SdlChannelEnd;
import hub.sam.sdl.SdlChannelPath;
import hub.sam.sdl.SdlGate;

/**
 * A sample validator interface for {@link hub.sam.sdl.SdlChannelEnd}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SdlChannelEndValidator {
	boolean validate();

	boolean validateAgent(SdlAgent value);
	boolean validateGate(SdlGate value);
	boolean validateOpposite(SdlChannelEnd value);
	boolean validateChannel(SdlChannelPath value);
}
