/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package hub.sam.sdl.validation;

import hub.sam.sdl.SdlAgentInstance;
import hub.sam.sdl.SdlInputInstance;
import hub.sam.sdl.SdlStateInstance;
import hub.sam.sdl.SdlStateStatus;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link hub.sam.sdl.SdlCompositeStateInstance}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SdlCompositeStateInstanceValidator {
	boolean validate();

	boolean validateActualState(SdlStateInstance value);
	boolean validateState(SdlStateInstance value);
	boolean validateInput(EList<SdlInputInstance> value);
	boolean validateOwningInstance(SdlAgentInstance value);
	boolean validateTriggered(SdlInputInstance value);
	boolean validateSender(SdlAgentInstance value);
	boolean validateStatus(SdlStateStatus value);
}
