/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package hub.sam.sdl.validation;

import hub.sam.sdl.SdlAgentType;
import hub.sam.sdl.SdlChannelEnd;
import hub.sam.sdl.SdlSignal;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link hub.sam.sdl.SdlGate}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SdlGateValidator {
	boolean validate();

	boolean validateReceive(EList<SdlSignal> value);
	boolean validateSend(EList<SdlSignal> value);
	boolean validateChannelEnd(EList<SdlChannelEnd> value);
	boolean validateAgentType(SdlAgentType value);
}
