/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package hub.sam.sdl.validation;

import hub.sam.sdl.EvaluationExpression;
import hub.sam.sdl.SdlGate;
import hub.sam.sdl.SdlSignal;

/**
 * A sample validator interface for {@link hub.sam.sdl.SdlOutput}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SdlOutputValidator {
	boolean validate();

	boolean validateSdlOutput_classifier(SdlSignal value);
	boolean validateVia(SdlGate value);
	boolean validateType(SdlSignal value);
	boolean validateTo(EvaluationExpression value);
}
