/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package hub.sam.sdl.validation;

import hub.sam.sdl.SdlAbstractState;
import hub.sam.sdl.SdlNamedState;
import hub.sam.sdl.SdlTransition;
import hub.sam.sdl.Start;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link hub.sam.sdl.SdlStateAutomaton}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SdlStateAutomatonValidator {
	boolean validate();

	boolean validateState(EList<SdlAbstractState> value);
	boolean validateTransition(EList<SdlTransition> value);
	boolean validateNamedState(EList<SdlNamedState> value);
	boolean validateStart(Start value);
}
