/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package hub.sam.sdl.validation;

import hub.sam.sdl.SdlAbstractState;
import hub.sam.sdl.SdlAction;
import hub.sam.sdl.SdlTrigger;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link hub.sam.sdl.SdlTransition}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SdlTransitionValidator {
	boolean validate();

	boolean validateAction(EList<SdlAction> value);
	boolean validateSource(SdlAbstractState value);
	boolean validateTarget(SdlAbstractState value);
	boolean validateTrigger(SdlTrigger value);
}
