/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package hub.sam.tef.tsl.validation;

import org.eclipse.emf.ecore.EClass;

/**
 * A sample validator interface for {@link hub.sam.tef.tsl.ElementBinding}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ElementBindingValidator {
	boolean validate();

	boolean validateMetaclass(EClass value);

	boolean validateBindingId(String value);
}
