/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package hub.sam.tef.tsl.validation;

import hub.sam.tef.tsl.ElementBinding;
import hub.sam.tef.tsl.NonTerminal;
import hub.sam.tef.tsl.Symbol;
import hub.sam.tef.tsl.ValueBinding;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link hub.sam.tef.tsl.Rule}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RuleValidator {
	boolean validate();

	boolean validateRhs(EList<Symbol> value);
	boolean validateLhs(NonTerminal value);
	boolean validateValueBinding(ValueBinding value);

	boolean validateElementBinding(ElementBinding value);

	boolean validatePriority(int value);
}
