/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package hub.sam.tef.tsl.validation;

import hub.sam.tef.tsl.NonTerminal;
import hub.sam.tef.tsl.Pattern;
import hub.sam.tef.tsl.Rule;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link hub.sam.tef.tsl.Syntax}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SyntaxValidator {
	boolean validate();

	boolean validateRules(EList<Rule> value);
	boolean validateStart(NonTerminal value);

	boolean validatePattern(EList<Pattern> value);

	boolean validateMetaModelPlatformURI(String value);
}
