/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.eclipse.emf.ocl.internal.cst.validation;

import org.eclipse.emf.ocl.internal.cst.InvOrDefCS;
import org.eclipse.emf.ocl.internal.cst.SimpleNameCS;

/**
 * A sample validator interface for {@link org.eclipse.emf.ocl.internal.cst.InvOrDefCS}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface InvOrDefCSValidator {
	boolean validate();

	boolean validateSimpleNameCS(SimpleNameCS value);
	boolean validateInvOrDefCS(InvOrDefCS value);
}
